if (LIBOCILIB_LIBRARIES AND LIBOCILIB_INCLUDE_DIRS)
set (LIBOCILIB_FIND_QUIETLY TRUE)
endif (LIBOCILIB_LIBRARIES AND LIBOCILIB_INCLUDE_DIRS)

find_path (LIBOCILIB_INCLUDE_DIRS NAMES ocilib.hpp)
find_library (LIBOCILIB_LIBRARIES NAMES ocilib)

include (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBOCILIB DEFAULT_MSG
LIBOCILIB_LIBRARIES LIBOCILIB_INCLUDE_DIRS)

mark_as_advanced(LIBOCILIB_INCLUDE_DIRS LIBOCILIB_LIBRARIES LIBOCILIB_FOUND)

Message("oclib found!")
Message("include dir:${LIBOCILIB_INCLUDE_DIRS}")
Message("library obj:${LIBOCILIB_LIBRARIES}")